export const adminModules = [
  {
    key: 'focusNews',
    label: '焦点新闻',
    titleField: 'title',
    slugField: 'slug',
    dateField: 'date',
    dateInputType: 'date',
    imageField: 'image',
    summaryField: 'summary',
    recommendedImageSize: '建议尺寸：1200 x 675 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: 'content',
    simple: true
  },
  {
    key: 'associationNotices',
    label: '协会公告',
    titleField: 'title',
    slugField: 'slug',
    dateField: 'date',
    dateInputType: 'date',
    imageField: 'image',
    summaryField: 'summary',
    recommendedImageSize: '建议尺寸：1200 x 675 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: 'content',
    simple: true
  },
  {
    key: 'internationalProjects',
    label: '国际宫健康管理工程',
    titleField: 'title',
    slugField: 'slug',
    dateField: 'date',
    dateInputType: 'date',
    imageField: 'image',
    summaryField: 'summary',
    recommendedImageSize: '建议尺寸：1200 x 675 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: 'content',
    simple: true
  },
  {
    key: 'expertVoices',
    label: '名家名说',
    titleField: 'name',
    titleLabel: '人物姓名（主标题）',
    slugField: 'slug',
    imageField: 'image',
    imageLabel: '人物照片地址',
    summaryField: 'quote',
    summaryLabel: '理念正文（核心内容）',
    recommendedImageSize: '建议尺寸：800 x 1000 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: 'insights',
    simple: true
  },
  {
    key: 'healthLecturesUpcoming',
    label: '专家健康大讲堂（近期讲座）',
    titleField: 'title',
    titleLabel: '讲座标题',
    slugField: 'slug',
    slugLabel: '讲座标识',
    dateField: 'dateTime',
    dateLabel: '开讲时间',
    dateInputType: 'datetime-local',
    imageField: 'avatar',
    imageLabel: '讲师头像地址',
    summaryField: 'summary',
    summaryLabel: '讲座摘要',
    recommendedImageSize: '建议尺寸：600 x 600 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: 'content',
    contentLabel: '讲座详情（每行一段）',
    extraFields: [
      { key: 'speaker', label: '主讲人', type: 'text' },
      { key: 'speakerTitle', label: '主讲人职称', type: 'text' },
      { key: 'location', label: '讲座地点', type: 'text' }
    ],
    simple: true
  },
  {
    key: 'healthLecturesReplay',
    label: '专家健康大讲堂（往期讲座回放）',
    titleField: 'title',
    titleLabel: '讲座标题',
    slugField: 'slug',
    slugLabel: '讲座标识',
    dateField: 'dateTime',
    dateLabel: '开讲时间',
    dateInputType: 'datetime-local',
    imageField: 'avatar',
    imageLabel: '讲师头像地址',
    summaryField: 'summary',
    summaryLabel: '讲座摘要',
    recommendedImageSize: '建议尺寸：600 x 600 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: 'content',
    contentLabel: '讲座详情（每行一段）',
    extraFields: [
      { key: 'speaker', label: '主讲人', type: 'text' },
      { key: 'speakerTitle', label: '主讲人职称', type: 'text' },
      { key: 'location', label: '讲座地点', type: 'text' },
      { key: 'videoUrl', label: '回放视频链接', type: 'url' }
    ],
    simple: true
  },
  {
    key: 'topicVideos',
    label: '专题视频',
    titleField: 'title',
    titleLabel: '视频标题',
    slugField: 'slug',
    slugLabel: '视频标识',
    imageField: 'coverImage',
    imageLabel: '封面图地址',
    summaryField: 'summary',
    summaryLabel: '视频摘要',
    recommendedImageSize: '建议尺寸：1200 x 675 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: '',
    simple: false
  },
  { key: 'trainingTracks', label: '培训方向', titleField: 'name', slugField: 'slug', imageField: '', summaryField: 'positioning', contentField: '', simple: false },
  { key: 'trainingCourses', label: '培训课程', titleField: 'name', slugField: 'slug', imageField: 'certificateImage', summaryField: 'summary', contentField: '', simple: false },
  { key: 'maternalTopics', label: '专题管理', titleField: 'title', slugField: 'slug', imageField: 'image', summaryField: 'positioning', contentField: '', simple: false },
  {
    key: 'homeHeroSlides',
    label: '首页轮播图',
    titleField: 'title',
    titleLabel: '轮播标题',
    slugField: 'slug',
    slugLabel: '轮播标识',
    imageField: 'image',
    imageLabel: '轮播图片地址',
    summaryField: 'subtitle',
    summaryLabel: '轮播副标题',
    recommendedImageSize: '建议尺寸：1200 x 400 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: '',
    simple: true
  },
  {
    key: 'homeLatestTips',
    label: '首页最新提示',
    titleField: 'title',
    titleLabel: '提示标题',
    slugField: 'slug',
    slugLabel: '提示标识',
    imageField: '',
    summaryField: 'text',
    summaryLabel: '提示文字',
    contentField: '',
    simple: true
  },
  {
    key: 'charityHomes',
    label: '公益家园',
    titleField: 'title',
    titleLabel: '项目名称',
    slugField: 'slug',
    slugLabel: '项目标识',
    imageField: 'image',
    imageLabel: '项目图片地址',
    summaryField: 'subtitle',
    summaryLabel: '项目简介',
    recommendedImageSize: '建议尺寸：400 x 400 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: '',
    extraFields: [
      { key: 'metric', label: '成效数据（如：已帮助 10,000+ 人）', type: 'text' }
    ],
    simple: true
  },
  {
    key: 'careWorkstations',
    label: '关爱工作站',
    titleField: 'title',
    titleLabel: '统计项标题',
    slugField: 'slug',
    slugLabel: '统计项标识',
    imageField: '',
    summaryField: 'subtitle',
    summaryLabel: '说明文案',
    contentField: '',
    extraFields: [
      { key: 'value', label: '展示数字（如：200+、50万+、98%）', type: 'text' }
    ],
    simple: true
  },
  {
    key: 'workstationGallery',
    label: '工作站展示',
    titleField: 'title',
    titleLabel: '图片标题（可选）',
    slugField: 'slug',
    slugLabel: '图片标识',
    imageField: 'image',
    imageLabel: '图片地址',
    summaryField: '',
    recommendedImageSize: '固定比例 4:3，建议尺寸：1200 x 900 像素，JPG/PNG，单张建议不超过 2MB',
    contentField: '',
    simple: true
  },
  {
    key: 'associationTeamStructure',
    label: '团队构成',
    titleField: 'roleTitle',
    titleLabel: '职务名称',
    slugField: 'roleKey',
    slugLabel: '职务标识',
    imageField: '',
    summaryField: '',
    contentField: '',
    simple: false
  },
  { key: 'products', label: '产品管理', titleField: 'name', slugField: 'slug', imageField: 'cover', summaryField: 'category', contentField: '', simple: false },
  { key: 'promoCategories', label: '项目推广分类', titleField: 'name', slugField: 'slug', imageField: '', summaryField: 'positioning', contentField: '', simple: false },
  { key: 'promoServices', label: '项目推广服务', titleField: 'title', slugField: 'slug', imageField: 'coverImage', summaryField: 'summary', contentField: '', simple: false }
];

export const moduleByKey = Object.fromEntries(adminModules.map((item) => [item.key, item]));
